// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvmmgamzacjzoeishjda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2bW1nYW16YWNqem9laXNoamRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NTU1OTcsImV4cCI6MjA3ODUzMTU5N30.fBYivDiGxAgRa_kmhqm9X4Q_Zo_aqu6t40B7kksvuPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});